# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a69b664f6242afc504629461b0af91681c7de931bbc67b511d49e7e1827f878cde0c3db5340d21538d0dd8678c5f81032f0d7d6226864ff98e5352f7c14f0c

test:
  secret_key_base: b2b71edae251dbbd7d8a812ad0c09871eb3eee70978cdb261afa743ab20763ce1648a4bd020a230b95e49842b62c290309d0cff7545095b9ff286f35915d8ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
